# Convert a list of UPDF results into a common 25-year posterior table.
#
# Usage (after creating out.list):
#   source("posterior_output.R")
#
# The resulting object, posterior.output, has one row per site and one column
# per 25-year interval.  When a UPDF period spans more than one 25-year
# interval, its posterior probability is apportioned according to the amount
# of time that falls in each interval.  Thus, each site's posterior values
# retain their original total probability (normally 1).  Site names are made
# unique if the same name appears more than once in out.list.
#
# This helper assumes each out.list entry was generated by updf() and contains
# site, posterior, and period components.  Source this file only after the
# analysis loop has created out.list.

posterior_by_interval <- function(out.list, interval = 25) {
  all_periods <- do.call(rbind, lapply(out.list, function(x) {
    as.matrix(x$period[, 1:2, drop = FALSE])
  }))
  earliest <- min(all_periods[, 1], na.rm = TRUE)
  latest <- max(all_periods[, 2], na.rm = TRUE)

  # UPDF dates are normally rounded to this interval.  Ceiling protects the
  # final interval if externally supplied output is not exactly aligned.
  bin_starts <- seq(earliest, latest, by = interval)
  bin_starts <- bin_starts[bin_starts < latest]
  if (length(bin_starts) == 0L) {
    bin_starts <- earliest
  }
  if (tail(bin_starts, 1L) + interval < latest) {
    bin_starts <- c(bin_starts, tail(bin_starts, 1L) + interval)
  }
  bin_ends <- bin_starts + interval
  interval_names <- paste0("AD_", bin_starts, "_", bin_ends)

  posterior_matrix <- matrix(
    0,
    nrow = length(out.list),
    ncol = length(bin_starts),
    dimnames = list(NULL, interval_names)
  )
  site_names <- character(length(out.list))

  for (i in seq_along(out.list)) {
    result <- out.list[[i]]
    periods <- as.matrix(result$period[, 1:2, drop = FALSE])
    posterior <- as.numeric(result$posterior)

    site_names[i] <- as.character(result$site[1])
    for (j in seq_len(nrow(periods))) {
      period_length <- periods[j, 2] - periods[j, 1]

      overlap <- pmax(
        0,
        pmin(periods[j, 2], bin_ends) - pmax(periods[j, 1], bin_starts)
      )
      posterior_matrix[i, ] <- posterior_matrix[i, ] +
        posterior[j] * overlap / period_length
    }
  }

  output <- data.frame(
    Site = make.unique(site_names),
    posterior_matrix,
    check.names = FALSE,
    row.names = NULL
  )
  output
}

# Create the requested table immediately when this file is sourced after the
# analysis loop. The function can also be called directly with another UPDF
# result list or a different interval length.
posterior.output <- posterior_by_interval(out.list)
